### ISSUE TITLE
Save only expansion parents to disk

### ISSUE THREAD

**Issue by schomatis** [nicola/r2#1]
The base ones depend on the seed so they're not reusable.

We should add the number of nodes and expansion size to the JSON filename to easily distinguish different dumps (those two variables should be enough to unequivocally determine the parents layout, for our fixed Fesitel key).

**Comment by nicola** [comment]
They are re-usable, the seed is the same across layers.

**Comment by schomatis** [comment]
Yes, but across layers you save parents _in memory_, I meant that across replications you're saving the generated parents in a JSON _file_, doesn't the seed change in each replication?

**Comment by nicola** [comment]
No, it does not.

There is one graph generated from a seed for all the network.

We may decided to update the graph at a later point. The “seed” that changes is part of the “replica_id”, but that doesn’t alter the shape of the graph.
