### ISSUE TITLE
`expander_parents`: use `permute` in the forward direction

### ISSUE THREAD

**Issue by schomatis** [nicola/r2#2]
https://github.com/nicola/r2/blob/afa6e4513f59e77b4082da2192cf4615137b21f2/src/graph.rs#L87

https://github.com/filecoin-project/rust-fil-proofs/blob/79b92f77b96209e387630d77bfa124b71c8610aa/storage-proofs/src/zigzag_graph.rs#L250-L257

**Comment by nicola** [comment]
thank you! done in f4edad89a2a30785e346f2a9f7a26fc165b8bf46
